### ISSUE TITLE
不支持嵌套在appbarlayout

### ISSUE THREAD

**Issue by onexuan** [Mixiaoxiao/OverScroll-Everywhere#3]
不支持嵌套在appbarlayout，希望得到支持

**Comment by Mixiaoxiao** [comment]
@onexuan 本质上是不行的。因为AppBarLayout这种ViewGroup中，如果RecyclerView越界滑动时，会通过NestedScroll机制传给父控件(即AppBarLayout)，实现滑动到头时可以继续拉着AppBarLayout把AppBar展开。而OverScroll实现的是越界滑动时自身弹性滑动（消耗掉这个滑动事件）
